[theme]
primaryColor = "#EF856B"              # 主色（橘粉，溫暖有食慾）
backgroundColor = "#FAE183"           # 背景色（淡黃，明亮好讀）
secondaryBackgroundColor = "#FFF7EC"  # 次背景（米白）
textColor = "#262730"                 # 字體顏色（保持深色）
font = "sans serif"

[server]
headless = true
enableCORS = false